name: "ç¼–è¯‘å†…æ ¸æ¨¡å—"

on:
  workflow_dispatch:

jobs:
  Set-repos:
    runs-on: ubuntu-latest

    steps:
      - name: "ğŸ˜„ Checkout"
        uses: actions/checkout@v3

      - name: "â­ Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev python-is-python3 python3 libarchive-tools dwarves libelf-dev

      - name: "ğŸŒŸ Clone kernel modules"
        run:          
          git clone https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 --depth=1

      - name: "Build kernel modulse"
        run: |
          pwd
          cd kernel_manifest
          repo sync -c -j$(nproc)
          
          ls -al
          ./kernel_platform/build/build_module.sh sun perf vendor/oplus/kernel/cpu/midas/oplus_bsp_midas.ko
