name: "ç¼–è¯‘å†…æ ¸æ¨¡å—"

on:
  workflow_dispatch:

jobs:
  Set-repos:
    runs-on: ubuntu-latest

    steps:
      - name: "ðŸ˜„ Checkout"
        uses: actions/checkout@v3

      - name: Free Disk Space
        run: |
          sudo docker image prune -a -f
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
        
      - name: "â­ Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip ftp \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp \
          zstd wget libfl-dev python-is-python3 python3 libarchive-tools \
          dwarves libelf-dev

      - name: "Downloading repo"
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "~/bin" >> $GITHUB_PATH

      - name: "ðŸŒŸ Clone kernel modules"
        run: |
          mkdir workspace
          cd workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 -m oneplus_13t_b.xml
          repo sync -c -j$(nproc) --depth=1

      - name: "Build kernel modulse"
        run: |
          pwd
          cd kernel_manifest
          
          ls -al
          ./kernel_platform/build/oplus_build_module.sh sun perf vendor/oplus/kernel/cpu/midas/oplus_bsp_midas.ko
